version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    environment:
      OPENAI_API_KEY: ""
      GROQ_API_KEY: ""
      GEMINI_API_KEY: ""
      OPENROUTER_API_KEY: ""
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
